targets:
    $default:
        builders:
            web3_contract_generator|web3_gen: {}

builders:
  web3_gen:
    target: ":web3_contract_generator"
    import: "package:web3_contract_generator/generator.dart"
    builder_factories: ["web3ContractGen"]
    build_extensions:
        '.abi': [".w3.dart"]
        '.abi.json': [".w3.dart"]
    auto_apply: dependents
    build_to: source
    defaults:
        generate_for:
            include:
                - "**/*.abi"
                - "**/*.abi.json"
