name: web3_contract_generator
description: A sample command-line application.
version: '0.1.0'
# version: 1.0.0
# homepage: https://www.example.com

environment:
  sdk: '>=2.10.0 <3.0.0'

dependencies:
  build: '^1.5.0'
  source_gen: ^0.9.0
  logger: ^0.9.4
  dartz: ^0.9.2
  json_annotation: ^3.1.0
  web3dart: ^1.2.3
  dart_style: ^1.3.7
  meta: ^1.2.3
  glob: ^1.2.0
  path: ^1.7.0
  logging: ^ 0.11.4

dev_dependencies:
  pedantic: ^1.9.0
  test: ^1.14.4
  build_test: ^1.2.2
  build_runner: ^1.10.3
  json_serializable: ^3.5.0
  source_gen_test: ^0.1.1
