name: web3_contract_generator
description: Generates dart classes corresponding to ABIs of Solidity smart contracts
version: 0.1.5
homepage: https://github.com/secure-vote/web3_contract_generator
repository: https://github.com/secure-vote/web3_contract_generator

environment:
  sdk: '>=2.10.0 <3.0.0'

dependencies:
  build: '^1.5.0'
  dartz: ^0.9.2
  web3dart: ^1.2.3
  dart_style: ^1.3.7
  meta: ^1.2.3
  path: ^1.7.0
  logging: ^ 0.11.4

dev_dependencies:
  pedantic: ^1.9.0
  test: ^1.14.4
  build_test: ^1.2.2
  build_runner: ^1.10.3
  web3_contract: ^0.1.1
