name: web3_contract
description: Supporting code for generated dart classes corresponding to ABIs of Solidity smart contracts
version: '0.1.5'
homepage: https://github.com/secure-vote/web3_contract_generator
repository: https://github.com/secure-vote/web3_contract_generator

environment:
  sdk: '>=2.10.0 <3.0.0'

dependencies:
  web3dart: ^1.2.3
  meta: ^1.2.3
  logging: ^ 0.11.4

dev_dependencies:
  test: ^1.14.4
