name: Dart Publish

on: push

jobs:
  build-and-publish:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - uses: cedx/setup-dart@v2
      - run: pub get
      - run: pub run test
      # - name: '>> Dart package <<'
      #   uses: k-paxian/dart-package-publisher@master
      #   with:
      #     accessToken: ${{ secrets.OAUTH_ACCESS_TOKEN }}
      #     refreshToken: ${{ secrets.OAUTH_REFRESH_TOKEN }}
