name: Dart Publish web3_contract

on: [push, pull_request]

jobs:
  build-and-publish:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: '>> Dart package (web3_contract) <<'
        uses: k-paxian/dart-package-publisher@master
        with:
          dryRunOnly: false
          accessToken: ${{ secrets.PUB_LISH_OAUTH_ACCESS_TOKEN }}
          refreshToken: ${{ secrets.PUB_LISH_OAUTH_REFRESH_TOKEN }}
          relativePath: web3_contract
